### ISSUE TITLE
Open Graph tags

### ISSUE THREAD

**Issue by avidsapp** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#26]
Have you had any issues with social media platforms displaying the correct images? See attached example. Also notice how it pulls the `<p>` tag into the open graph card too.

<img width="496" alt="Screen Shot 2021-05-13 at 10 11 09 PM" src="https://user-images.githubusercontent.com/11481762/118220420-46491280-b441-11eb-8ede-eb12614d9eae.png">

Facebook sharing debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fecotourismbelize.com%2Fecotourism-belizes-covid-19-measures-is-providing-a-safer-environment%2F

**Comment by henrikwirth** [comment]
Hi @avidsapp, if you look into this file, you can see that no image is used in the Seo component yet.
https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty/blob/master/src/components/Seo.js

You have to add it to the GraphQL query and then use it in the Seo (react-helmet) component.

Also you probably want to get rid of the `<p>` tag in your Seo description.

**Comment by henrikwirth** [comment]
I opened a PR #27 to fix the images and the url/canonical issues. You need to add your frontend URL to the .env file.

I can't fix the problem with the description, since it the data comes that way from gatsby-source-wordpress. The best way to do SEO properly is to use some WPGraphQL supported SEO plugin. For example YoastSEO. Then you can create proper descriptions from it and also adjust other values depending on your needs.

**Comment by henrikwirth** [comment]
Merged it into `master`. Make sure to clear your cache before rebuilding. `yarn clean`

**Comment by avidsapp** [comment]
That did the trick. Thanks for the quick turnaround as always!
